AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    megaphone-validator

    Sample SAM Template for megaphone-validator

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Resources:

    MegaphoneValidatorFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: megaphone-validator/
            Handler: index.handler
            Runtime: nodejs8.10
            MemorySize: 512
            Timeout: 900
            Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    PARAM1: VALUE
            Events:
                MegaphoneValidator:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /megaphone-validator
                        Method: get

Outputs:

    MegaphoneValidatorApi:
      Description: "API Gateway endpoint URL for Prod stage for MegaphoneValidator function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/megaphone-validator/"

    MegaphoneValidatorFunction:
      Description: "MegaphoneValidator Lambda Function ARN"
      Value: !GetAtt MegaphoneValidatorFunction.Arn

    MegaphoneValidatorFunctionIamRole:
      Description: "Implicit IAM Role created for MegaphoneValidator function"
      Value: !GetAtt MegaphoneValidatorFunctionRole.Arn
